name: .NET Code Analysis with StyleCop

on:
  push:
    branches: [ " * " ]
  pull_request:
    branches:
      - main

jobs:
  stylecop:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run StyleCop Analysis on all files
        run: |
          dotnet format --verify-no-changes --severity warn
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal
